#!/data/data/com.termux/files/usr/bin/bash


checkdependencies()
{
    if [ -e ~/../usr/bin/java ] && [ -e ~/../usr/bin/python ] && [ -e ~/../usr/bin/wget ] && [ -e ~/../usr/bin/dialog ] && [ -e ~/../usr/bin/tput ] && [ -e ~/../usr/bin/jq ] && [ "$(find ~/../usr/lib/ -name "wheel" | wc -l)" != "0" ] && [ "$(find ~/../usr/lib/ -name "requests" | wc -l)" != "0" ] && [ "$(find ~/../usr/lib/ -name "bs4" | wc -l)" != "0" ] && [ -e ~/../usr/bin/revancify ]
    then
        return 0
    else
        return 1
    fi
}

installdependencies()
{
    echo "Installing dependencies..."
    sleep 0.5s
    git pull
    pkg update -y &&
    pkg install python openjdk-17 wget ncurses-utils dialog jq -y
    pip install --upgrade pip
    pip install wheel
    pip install requests bs4
    cp revancify ~/../usr/bin
    sleep 0.5s
    echo "Dependencies installed successfully."
}

checkrevancify()
{
    if cd ~/storage/Revancify > /dev/null 2>&1 
    then
        return 0
    else
        echo "Revancify is not installed"
        exit
    fi
}

if ping -c 1 google.com > /dev/null 2>&1
then
    checkrevancify
    if checkdependencies
    then
        tput civis
        rm -rf ./*cache
        git checkout . > /dev/null 2>&1
        git pull > /dev/null 2>&1
        cp dialog-config.txt ~/.dialogrc
        cp revancify ~/../usr/bin/revancify
        bash revancify.sh
        clear
    else
        installdependencies
    fi
else
    checkrevancify
    if checkdependencies
    then
        tput civis
        rm -rf ./*cache
        bash revancify.sh
    else
        echo "Dependencies not installed. Run again with internet connection."
        exit
    fi
fi